# Generated by Django 4.1.1 on 2022-09-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_car_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.IntegerField(default='Null'),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.DateField(default='Null'),
        ),
    ]
